FROM python:3.7.1-alpine

WORKDIR /app/django/

# We need the Postgres client and pipenv installed
RUN apk update && apk add postgresql-dev gcc g++ python3-dev musl-dev
RUN pip install pipenv

COPY ./Pipfile* /app/django/
RUN pipenv install --deploy --system

COPY ./politweetalyzer /app/django/politweetalyzer
COPY ./politweets /app/django/politweets
COPY ./client/dist /app/django/client/dist
COPY ./manage.py /app/django/
COPY ./scripts /app/django/scripts

CMD ./scripts/runserver
