version: '3.7'
services:
    postgres:
        image: 'postgres:10.5-alpine'
        restart: always
        environment:
            POSTGRES_USER: 'politweets'
            POSTGRES_PASSWORD: 'politweets'
        ports:
            - '15432:5432'
    webpack:
        image: webpack-politweetalyzer
        build:
            context: .
            dockerfile: ./docker/Dockerfile-webpack
        volumes:
            - ./client/src/:/app/node/src
            - ./client/dist:/app/node/dist
