# Generated by Django 2.1.2 on 2018-10-12 19:15

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propublica_id', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('chamber', models.CharField(choices=[('S', 'Senate'), ('H', 'House')], max_length=1)),
                ('party', models.CharField(choices=[('R', 'Republican'), ('D', 'Democrat'), ('I', 'Independent')], max_length=1)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True, help_text='Still in office')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_tweet_id', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='politweets.Member')),
            ],
        ),
    ]
