# Generated by Django 2.1.2 on 2018-10-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0002_auto_20181017_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='link',
        ),
    ]
