# Generated by Django 2.1.2 on 2018-10-19 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0004_auto_20181017_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'get_latest_by': 'time', 'ordering': ['-time']},
        ),
    ]
