# Generated by Django 2.1.2 on 2018-11-05 22:05

import json

from django.db import migrations


def tweet_data_to_json(tweet):
    stringy_json = tweet.original_data
    # If it's a string, convert it. Otherwise, do nothing.
    if isinstance(stringy_json, str):
        object_json = json.loads(stringy_json)
        tweet.original_data = object_json
        tweet.save()


def tweet_data_to_string(tweet):
    object_json = tweet.original_data
    stringy_json = json.dumps(object_json)
    tweet.original_data = stringy_json
    tweet.save()


def forward(apps, schema_editor):
    Tweet = apps.get_model('politweets', 'Tweet')
    tweets = Tweet.objects.all()
    for tweet in tweets:
        tweet_data_to_json(tweet)


def reverse(apps, schema_editory):
    Tweet = apps.get_model('politweets', 'Tweet')
    tweets = Tweet.objects.all()
    for tweet in tweets:
        tweet_data_to_string(tweet)


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0006_auto_20181029_0103'),
    ]

    operations = [
        migrations.RunPython(forward, reverse, elidable=True)
    ]
