# Generated by Django 2.1.2 on 2018-11-05 22:37

from django.db import migrations


def forward(apps, schema_editor):
    "Delete all tweets that are retweets"
    Tweet = apps.get_model('politweets', 'Tweet')
    retweets = Tweet.objects.filter(
        original_data__retweeted_status__isnull=False
    )
    retweets.delete()


def reverse(apps, schema_editor):
    "There is no good way to restore deleted tweets"
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0007_original_data_to_json'),
    ]

    operations = [
        migrations.RunPython(forward, reverse, elidable=True)
    ]
