# Generated by Django 2.1.3 on 2018-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0010_update_old_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
