# Generated by Django 2.1.3 on 2019-01-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politweets', '0011_member_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active',
        ),
        migrations.AddField(
            model_name='member',
            name='session',
            field=models.PositiveIntegerField(default=115),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['session'], name='politweets__session_55bd58_idx'),
        ),
    ]
