FROM node:10.13.0-alpine
WORKDIR /app/node/

COPY ./client/package*.json /app/node/
RUN npm install

COPY ./client/config/ /app/node/config
COPY ./client/scripts/ /app/node/scripts

# The source and destination directories must be mounted as volumes at
# /app/node/src and /app/node/dist, respectively
CMD npm run watch
