FROM python:3.7.1-alpine

WORKDIR /app/django/

# We need the Postgres client and pipenv installed
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install pipenv

COPY ./Pipfile* /app/django/
RUN pipenv install

# The Django code must be provided as a volume mounted at /app/django
CMD pipenv run ./manage.py runserver 0.0.0.0:8000
