export const BAR_HEIGHT = 10
export const TWEET_NODE_WIDTH = BAR_HEIGHT
export const TWEET_NODE_GUTTER = 1
export const ROW_HEIGHT = BAR_HEIGHT * 2 + TWEET_NODE_GUTTER
export const ROW_GUTTER = 4
export const LABEL_WIDTH = 75
export const GUTTER = 10
export const BAR_MAX_WIDTH = window.innerWidth > 450 ? 300 : 150
export const COUNT_LABEL_WIDTH = 75
export const CHART_WIDTH = LABEL_WIDTH * 2 + GUTTER * 2 + BAR_MAX_WIDTH
