#!/usr/bin/env sh

# Run the Django server. This script is to be run from the live
# Heroku container. It _must_ be run from the project root.

./manage.py collectstatic --noinput --settings politweetalyzer.settings.prod
./manage.py migrate --settings politweetalyzer.settings.prod
gunicorn politweetalyzer.wsgi
